# export COMPOSE_DOCKER_CLI_BUILD=0 # some machines need for smooth --build
# .env file: TEST_DATA_DIR=<local parent directory of workflow_ephys_data{1,2}>
# docker-compose -f ./docker/docker-compose-test.yaml up --build
# docker exec -it workflow-visual-stimulus_workflow_1 /bin/bash
# docker-compose -f ./docker/docker-compose-test.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-visual-stimulus-test-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-visual-stimulus/docker/Dockerfile.test
    env_file: .env
    image: workflow-visual-stimulus-test:0.0.0a0
    container_name: workflow-visual-stimulus-test
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - DATABASE_PREFIX=test_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest -sv --cov-report term-missing --cov=workflow_visual_stimulus -p no:warnings tests/
        tail -f /dev/null
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-trial:/main/element-trial # ?
      - ../../element-visual-stimulus:/main/element-visual-stimulus
      - ..:/main/workflow-visual-stimulus
    depends_on:
      db:
        condition: service_healthy
networks:
  main:
