FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-visual-stimulus/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

WORKDIR /main/workflow-visual-stimulus

# Option 1 - Install DataJoint's remote fork of the workflow and elements
# RUN git clone https://github.com/datajoint/workflow-visual-stimulus.git /main/

# Option 2 - Install user's remote fork of element and workflow
#            or an unreleased version of the element
# RUN pip install git+https://github.com/<user>element-lab.git
# RUN pip install git+https://github.com/<user>/element-animal.git
# RUN pip install git+https://github.com/<user>/element-session.git
# RUN pip install git+https://github.com/<user>/element-trial.git
# RUN pip install git+https://github.com/<user>/element-electrode-localization.git
# RUN pip install git+https://github.com/<user>/element-visual-stimulus.git
# RUN git clone https://github.com/<user>/workflow-visual-stimulus.git /main/workflow-visual-stimulus

# Option 3 - Install user's local fork of element and workflow
RUN mkdir -p /main/element-lab \
             /main/element-animal \
             /main/element-session \
             /main/element-trial \
             /main/element-visual-stimulus \
             /main/workflow-visual-stimulus

COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-trial /main/element-trial
COPY --chown=anaconda:anaconda ./element-electrode-localization /main/element-electrode-localization
COPY --chown=anaconda:anaconda ./element-visual-stimulus /main/element-visual-stimulus
COPY --chown=anaconda:anaconda ./workflow-visual-stimulus /main/workflow-visual-stimulus

RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-trial
RUN pip install -e /main/element-electrode-localization
RUN pip install -e /main/element-visual-stimulus
# RUN rm -f /main/workflow-visual-stimulus/dj_local_conf.json

# Install the workflow
RUN pip install /main/workflow-visual-stimulus
RUN pip install -r /main/workflow-visual-stimulus/requirements_test.txt
