# docker-compose -f ./docker/docker-compose-dev.yaml up -d --build
# docker-compose -f ./docker/docker-compose-dev.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-visual-stimulus-dev-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-visual-stimulus/docker/Dockerfile.dev
    env_file: .env
    image: workflow-visual-stimulus-dev:0.0.0a0
    container_name: workflow-visual-stimulus-dev
    environment:
      - EPHYS_ROOT_DATA_DIR=/main/test_data/workflow_ephys_data1/,/main/test_data/workflow_ephys_data2/
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-trial:/main/element-trial
      - ../../element-visual-stimulus:/main/element-visualstimulus
      - ..:/main/workflow-visual-stimulus
    depends_on:
      visual-stimulus-dev-db:
        condition: service_healthy
networks:
  main:
